# Generated by Django 5.2.4 on 2026-04-03 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financialrecord',
            name='description',
        ),
        migrations.AddField(
            model_name='financialrecord',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financialrecord',
            name='amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='financialrecord',
            name='category',
            field=models.CharField(max_length=50),
        ),
    ]
